#!/usr/bin/env python
import argparse

from alppaca.main import run_scheduler_and_webserver
from alppaca.util import load_config


def main():
    args = parse_arguments()
    config = load_config(args.config)
    run_scheduler_and_webserver(config)


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-c', '--config', help="Alppaca YAML config file", type=str,
        default='/etc/alppaca/config.yaml')

    return parser.parse_args()


main()
