#!/usr/bin/env python

import argparse
import sys

from succubus import Daemon

from afp_alppaca.main import run_scheduler_and_webserver
from afp_alppaca.util import load_config


class AlppacaDaemon(Daemon):
    def run(self):
        run_scheduler_and_webserver(self.config)

    def parse_arguments(self):
        parser = argparse.ArgumentParser()
        parser.add_argument(
            '-c', '--config', help="Alppaca YAML config directory", type=str,
            default='/etc/alppaca')

        return parser.parse_args()

    def load_configuration(self):
        args = self.parse_arguments()
        self.config = load_config(args.config)


if __name__ == "__main__":
    # FIXME: Use proper pid file directory
    alppaca = AlppacaDaemon(pid_file="/var/run/alppacad/alppacad.pid")
    sys.exit(alppaca.action())
