#!/usr/bin/env python

import argparse

from succubus import Daemon

from afp_alppaca.main import run_scheduler_and_webserver
from afp_alppaca.util import load_config


class AlppacaDaemon(Daemon):
    def run(self):
        args = self.parse_arguments()
        config = load_config(args.config)
        run_scheduler_and_webserver(config)

    def parse_arguments(self):
        parser = argparse.ArgumentParser()
        parser.add_argument(
            '-c', '--config', help="Alppaca YAML config directory", type=str,
            default='/etc/alppaca')

        return parser.parse_args()


if __name__ == "__main__":
    # FIXME: Use proper pid file directory
    alppaca = AlppacaDaemon(pidfile="/tmp/alppaca.pid")
    alppaca.action()
